@startuml Vehiculo
class Vehiculo {
    -marca : String
    +arrancar() : void
}
class Coche {
    -numPuertas : int
    +conducir() : void
}
class Motor {
    -cilindrada : int
}
class Rueda {
    -presion : float
}
class Conductor {
    -nombre : String
}
Vehiculo <|-- Coche
Coche "1" *-- "1" Motor : tiene
Coche "1" o-- "4" Rueda : usa
Conductor "1" -- "0..*" Coche : conduce
@enduml