<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="nombre" type="xs:string"/>
  
  <xs:element name="matricula">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="personal"/>
        <xs:element ref="pago"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="personal">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="dni" type="xs:string"/>
        <xs:element ref="nombre"/>
        <xs:element name="titulacion" type="xs:string"/>
        <xs:element name="curso_academico" type="xs:string"/>
        <xs:element name="domicilios" type="TipoDomicilio"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:complexType name="TipoDomicilio">
    <xs:sequence>
      <xs:element ref="domicilio" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="domicilio">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre"/>
      </xs:sequence>
      <xs:attribute name="tipo" type="xs:string"/>
    </xs:complexType>
    
  </xs:element>
  
  
  <xs:element name="pago">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="tipo_matricula" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
</xs:schema>
